# Generated by Django 5.2.7 on 2025-11-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('fertilizer', 'Fertilizer'), ('pesticide', 'Pesticide'), ('seed', 'Seed'), ('tool', 'Tool'), ('equipment', 'Equipment')], max_length=50)),
                ('price', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.CharField(default='📦', max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('reviews', models.IntegerField(default=0)),
                ('seller', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
